### ISSUE TITLE
Request :)

### ISSUE THREAD

**Issue by ASopH** [ghDaYuYu/foo_run_xgrp#1]
Any Chance for a 64bit version ... o.O
many thanks

**Comment by ghuDaYuYu** [comment]
I could build the 64bit version, but unfortunately, I do not have time to test it.

Would you provide testing and test reports?

Also, consider if the following issues/limitations would constitute a problem:
- The preference page is not fully implemented in the original sources (dark mode, reset and apply functionality won´t be available for the moment).
- Windows 7 min. requirement.

**Comment by ASopH** [comment]
Sure, I try my very best ^^

**Comment by ghuDaYuYu** [comment]
Great! I believe my use case was related to running ADB push commands. It will be awesome if you can provide some description of your current use case, the component configuration and hopefully successful test results, thanks!

[foo_run_xgrp v1.0.5.zip](https://github.com/ghDaYuYu/foo_run_group/files/11614887/foo_run_xgrp.v1.0.5.zip)

**Comment by ASopH** [comment]
First run: fantastic - as expected.
My current use is: I'm convertig album art for implemtation for my portable player. with foo_run I must touch every album by album by album.
As you said, the configuration window is in bright view - not so important for me - the function counts...
In the configuration I only entered the name and the command line, otherwise nothing else changed.

![RSPG](https://github.com/ghDaYuYu/foo_run_group/assets/14108704/0fb24edc-ba37-4f67-9635-23939599e720)

I had selected "Wait Progress" for testing. The process bar was in dark mode. 
I had selected "Minimize Window" for testing. Works as expected.
I don't know what "Reload Info when Finished" do ... not important ... only to know. 

Many thanks for your effort 👍 

ToDo: Configuration Window in dark mode (but not for me)

**Comment by ghuDaYuYu** [comment]
Thanks for reporting, I bet the original coder would also be chaffed to know about this!
I'll try to include dark mode and round off the preference page when I find some spare time.
Best regards!

**Comment by ghuDaYuYu** [comment]
A new preview release adding dark mode and a reworked preferences page is available...
no obligation is implied indeed, feel free to try it out if you feel like it.

About the "Reload Info when Finished" I guess it should refresh fb2k's database after running commands that changed file metadata. I've never used that option before.

Regards!

[foo_run_xgrp v1.1.0 preview](https://github.com/ghDaYuYu/foo_run_xgrp/releases/tag/v1.1.0)

**Comment by ghuDaYuYu** [comment]
v1.1.0 preview release update:
- fixed service list drag and drop.

**Comment by ASopH** [comment]
Hi,
thank you for work. As far I can say: all ok from my side! Good work

**Comment by ghuDaYuYu** [comment]
Thanks for testing!
I am closing the issue, may reopen to notify new updates.
