### ISSUE TITLE
Settings window glitch

### ISSUE THREAD

**Issue by amigx** [ghDaYuYu/foo_run_xgrp#2]
@ghuDaYuYu,
-The component window needs to be slightly corrected (see pic):

![pic3](https://github.com/ghDaYuYu/foo_run_xgrp/assets/142154525/80f1249f-1675-425b-b6b3-be990c7aad2f)

-The font in the settings window differs from the font of the settings windows of other components. This can be seen for example by the letter "a".

Thank You!

**Comment by ghuDaYuYu** [comment]
[v1.1.1](https://github.com/ghDaYuYu/foo_run_xgrp/releases) should fix it... thanks for reporting 👍

**Comment by ghuDaYuYu** [comment]
Closing as fix has been confirmed.
